autoformat

diff --git a/production_server b/production_server
--- a/production_server
+++ b/production_server
@@ -3,16 +3,16 @@
 DEFAULT_SECRET="${HOME}/vps/secret"
 
 if [ -e "$1" ]; then
-  FILEPATH="${1}"
-  shift
+	FILEPATH="${1}"
+	shift
 else
-  if [ -e "$DEFAULT_SECRET" ]; then
-    FILEPATH="${HOME}/vps/secret"  # default location on my server
+	if [ -e "$DEFAULT_SECRET" ]; then
+		FILEPATH="${HOME}/vps/secret" # default location on my server
 
-  else
-    echo "Error: Pass JSON config file as first argument" 1>&2
-    exit 1
-  fi
+	else
+		echo "Error: Pass JSON config file as first argument" 1>&2
+		exit 1
+	fi
 fi
 
 if [ ! -e "$FILEPATH" ]; then
@@ -28,19 +28,19 @@ export TMDB_API_KEY=$(jq -r '.tmdb_api_key' "$FILEPATH")
 export MIX_ENV=prod
 
 case "$1" in
-  # drop into an interactive shell after loading environment secrets
-  -i)
-    echo "Dropping into interactive shell with secrets..."
-    bash
-    exit 0
-    ;;
-  --iex)
-    # drop into iex after loading environment secrets
-    iex -S mix
-    exit 0
-    ;;
-  *)
-  ;;
+# drop into an interactive shell after loading environment secrets
+-i)
+	echo "Dropping into interactive shell with secrets..."
+	bash
+	exit 0
+	;;
+--iex)
+	# drop into iex after loading environment secrets
+	iex -S mix
+	exit 0
+	;;
+*) ;;
+
 esac
 
 mix deps.get --only prod
